bash

diff --git a/bash_script b/bash_script
--- a/bash_script
+++ b/bash_script
@@ -42,15 +42,16 @@ fi
 #     ((n+=1))
 # done
 
-n=0
-command=$1
-while ! $command && [ $n -le 5 ]; do
-    sleep $n
-    ((n=n+1))
-    echo "Retry #$n"
-done;
+# n=0
+# command=$1
+# while ! $command && [ $n -le 5 ]; do
+#     sleep $n
+#     ((n=n+1))
+#     echo "Retry #$n"
+# done;
 
 
+# for loops
 
 
 
